name: Test pubblicazione telegram ogni minuto

on:
  schedule:
    - cron: '*/1 * * * *'  # ogni minuto
  workflow_dispatch:

jobs:
  send-telegram-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install openpyxl requests
      - name: Run send_menu.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_menu.py
      - name: Commit virtual_today.txt
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add virtual_today.txt
          git commit -m "Avanza giorno virtuale" || echo "No changes"
          git push
