name: Pubblica menu Telegram ogni giorno

on:
  schedule:
    - cron: '0 6 * * 1-5'  # Alle 08:00 ora italiana, lunedì-venerdì (1-5)
  workflow_dispatch:

jobs:
  send-telegram-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install openpyxl requests
      - name: Run send_menu.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_menu.py
