name: Post MensaCC to Telegram

on:
  workflow_dispatch:         # permette di lanciare a mano il workflow da Actions
  schedule:
    - cron: '*/5 * * * *'   # ogni 5 minuti (ogni 10 non si può)

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Get Mess.txt and send to Telegram
        run: |
          MSG=$(curl -s https://raw.githubusercontent.com/DevNullCC/MensaCC/main/Mess.txt)
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" --data-urlencode "text=$MSG"
